Repository half-blue/A_plus_Tsukuba, pull requests merged in 2023-09, with the labels that each got.

#118 Rank-function
  board/models.py
  board/static/board/Aplus-tsukuba-01.png
  board/static/board/Aplus-tsukuba-02.png
  board/static/board/Aplus-tsukuba-03.png
  board/static/board/Aplus-tsukuba-04.png
  board/static/board/Aplus-tsukuba-05.png
  board/static/board/chat.css
  board/static/board/col7.js
  board/static/board/common.css
  board/static/board/common.js
  board/static/board/search.css
  board/static/board/search.js
  board/static/board/send.js
  board/templates/board/Chat.html
  board/templates/board/Search.html
  board/templates/col7.html
  board/templates/send.html
Labels: enhancement

#123 コメントする時に感情が全部表示されないバグの修正
  board/static/board/send.js
Labels: bug

#122 教科書アマゾンアソシエイト＋Prime Student広告実装
  board/admin.py
  board/models.py
  board/static/board/chat.css
  board/static/board/common.js
  board/static/board/textbooks.js
  board/templates/board/Chat.html
  board/templates/board/Search.html
  board/templates/col5.html
  board/templates/textbooks.html
  board/views.py
Labels: enhancement, PoC
